"""Creates the repository that holds the `toolchain()` declarations.

This follows the guidance at
https://bazel.build/extending/toolchains#toolchain-resolution:

"
Note that in order to resolve toolchains in the analysis phase Bazel needs to
analyze all toolchain targets that are registered. Bazel will not need to
analyze all targets referenced by toolchain.toolchain attribute. If in order to
register toolchains you need to perform complex computation in the repository,
consider splitting the repository with toolchain targets from the repository
with <LANG>_toolchain targets. Former will be always fetched, and the latter
will only be fetched when user actually needs to build <LANG> code.
"

The "complex computation" here is downloading a ~100 GB installer archive and
running an unattended Vivado install that can take tens of minutes. This hub
repository is cheap -- it is a single generated `BUILD.bazel` -- and everything
it needs is known from the `vivado.install` tag's attributes, so registering the
toolchain never triggers an install. The install happens only once a
`vivado_*` action actually resolves to this toolchain and Bazel analyses
`@vivado_<name>//:vivado_toolchain`.

When no installation is configured the hub is generated empty. A module that
merely depends on `toolchains_vivado` without configuring it therefore sees "no
Vivado toolchain registered" rather than a hard failure at fetch time.
"""

_HEADER = """\
# Generated by //vivado/private:toolchains_repo.bzl. Do not edit.
#
# These toolchains are registered by toolchains_vivado's MODULE.bazel via
# `register_toolchains("@vivado_toolchains//:all")`, so you do not normally need
# to reference these targets yourself. They can also be passed to
# --extra_toolchains.

package(default_visibility = ["//visibility:public"])
"""

_EMPTY_NOTE = """\
# No `vivado.install(...)` tag was declared by the root module, so there is
# nothing to register. Add one to MODULE.bazel to provision Vivado:
#
#     vivado = use_extension(
#         "@toolchains_vivado//vivado:extensions.bzl",
#         "vivado",
#     )
#     vivado.install(
#         urls = ["file:///path/to/FPGAs_AdaptiveSoCs_Unified_SDI_2025.2.tar"],
#         sha256 = "...",
#         modules = ["Artix-7"],
#     )
"""

_TOOLCHAIN = """
toolchain(
    name = "{name}_toolchain",
    exec_compatible_with = {exec_compatible_with},
    toolchain = "@{repo}//:vivado_toolchain",
    toolchain_type = "@rules_vivado//vivado:toolchain_type",
)
"""

def _toolchains_repo_impl(repository_ctx):
    content = _HEADER
    installs = repository_ctx.attr.installs
    if not installs:
        content += "\n" + _EMPTY_NOTE

    for name in installs:
        version = repository_ctx.attr.versions.get(name, "")
        constraints = ["@platforms//os:linux"]

        # Opt-in only. A stock host platform declares no Vivado version
        # constraint, so registering one unconditionally would make this
        # toolchain unselectable. See the `register_version_constraint`
        # attribute of the `vivado.install` tag.
        if name in repository_ctx.attr.version_constrained and version:
            constraints.append(
                "@rules_vivado//vivado/constraints/version:" + version,
            )
        content += _TOOLCHAIN.format(
            exec_compatible_with = repr(constraints),
            name = name,
            repo = installs[name],
        )

    repository_ctx.file("BUILD.bazel", content)

    # Bazel <8.3.0 lacks rctx.repo_metadata.
    if not hasattr(repository_ctx, "repo_metadata"):
        return None

    # The contents are fully determined by the attributes, so this repository
    # can be reproducibly refetched and cached across workspaces.
    return repository_ctx.repo_metadata(reproducible = True)

toolchains_repo = repository_rule(
    _toolchains_repo_impl,
    doc = "Creates a repository with the Vivado `toolchain()` declarations, " +
          "kept separate from the (expensive) installation repositories so " +
          "that toolchain resolution never triggers an install.",
    attrs = {
        "installs": attr.string_dict(
            doc = "Maps each install name to the repository holding its " +
                  "`vivado_toolchain` target.",
        ),
        "version_constrained": attr.string_list(
            doc = "Install names whose `toolchain()` should additionally " +
                  "carry a `@rules_vivado//vivado/constraints/version:<X.Y>` " +
                  "constraint.",
        ),
        "versions": attr.string_dict(
            doc = "Maps each install name to its Vivado version, used for the " +
                  "version constraint.",
        ),
    },
)
